include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    sort_constructors_first: true
    sort_pub_dependencies: true
    avoid_print: true
    avoid_relative_lib_imports: true
    avoid_unnecessary_containers: true
    prefer_single_quotes: true
    prefer_const_constructors: true
    prefer_int_literals: true
    always_use_package_imports: true
    always_put_required_named_parameters_first: true
    always_specify_types: true
    omit_local_variable_types: false
    public_member_api_docs: false
    require_trailing_commas: true
    avoid_empty_else: true
    avoid_init_to_null: true
    avoid_types_as_parameter_names: true
    prefer_final_locals: true
    prefer_is_not_empty: true
    unawaited_futures: true
