// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-CdLkpB0oOMo4xCKBQ0tJ-aBSiQwDRhU',
    appId: '1:993672599625:web:23387b5f81150e93470798',
    messagingSenderId: '993672599625',
    projectId: 'getsh-tdone',
    authDomain: 'getsh-tdone.firebaseapp.com',
    storageBucket: 'getsh-tdone.firebasestorage.app',
    measurementId: 'G-NSSBRPDKGE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4x2E8VsF8OE5ELN6dL6wJsI4Y2m2SyM8',
    appId: '1:993672599625:android:01ec789dffe23641470798',
    messagingSenderId: '993672599625',
    projectId: 'getsh-tdone',
    storageBucket: 'getsh-tdone.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCk2JwbgxUb9Whe9kzocKFrJYX3ZWDaIQ8',
    appId: '1:993672599625:ios:2b76ad4bdc81fc1c470798',
    messagingSenderId: '993672599625',
    projectId: 'getsh-tdone',
    storageBucket: 'getsh-tdone.firebasestorage.app',
    iosBundleId: 'dev.plotsklapps.getshtdone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCk2JwbgxUb9Whe9kzocKFrJYX3ZWDaIQ8',
    appId: '1:993672599625:ios:2b76ad4bdc81fc1c470798',
    messagingSenderId: '993672599625',
    projectId: 'getsh-tdone',
    storageBucket: 'getsh-tdone.firebasestorage.app',
    iosBundleId: 'dev.plotsklapps.getshtdone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0SWNF9b-YloFgv3FqYbjc9N_JqGO6AvM',
    appId: '1:993672599625:web:f8a3ec24c187adc6470798',
    messagingSenderId: '993672599625',
    projectId: 'getsh-tdone',
    authDomain: 'getsh-tdone.firebaseapp.com',
    storageBucket: 'getsh-tdone.firebasestorage.app',
    measurementId: 'G-9FCTZJXCYN',
  );

}